# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5433         
  username: postgres
  password: postgres  
  pool: 5

development:
  <<: *default
  database: team_task_manager_development

test:
  <<: *default
  database: team_task_manager_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>