database:
  - name : team_task_manager_development
    databaseName : team_task_manager_development
    user: taem_task_manager_development
    plan: free

services:
  - type: web
    name: team_task_manager_development
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: team_task_manager_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2